import type { Metadata } from "next";
import "../globals.css";
import {Toaster} from "react-hot-toast"
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "Shopcart Online Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
          <Header />
            <main className={`flex-1`}>{children}
              <Toaster
              position="bottom-right"
              toastOptions={{
                style: {
                  background: "#000000",
                  color: "#fff"
                }
              }} 
              />
            </main>
          <Footer />
    </ClerkProvider>
  );
}
